Перенос приложения на Node.js
ottenokLeshi/trafficJamsApi pull request #4
Opened 2016-11-30 21:54 UTC by ottenokLeshi

2016-12-07 11:40 UTC, MadMed677 requested changes

2016-12-07 11:40 UTC, MadMed677 commented on package.json
> +    "start": "node ./server_side/index.js"
То есть клиентский запуск уже не нужен?

2016-12-07 11:40 UTC, MadMed677 commented on package.json
> +    "webpack": "1.13.3"
Зачем оставил webpack?

2016-12-07 11:40 UTC, MadMed677 commented on server_side/index.js
> +let server = require("./server");
Принято не изменяемые данные создавать как `const`

2016-12-07 11:40 UTC, MadMed677 commented on server_side/requestHandlers.js
> +const getRoutes = (response) => {
JSDoc,  пожалуйста

2016-12-07 11:40 UTC, MadMed677 commented on server_side/requestHandlers.js
> +const start = (response) => {
JSDoc,  пожалуйста.
Лишний отступ на 9'ой строке

2016-12-07 11:40 UTC, MadMed677 commented on server_side/route.js
> +const route = (handle, pathname, response) => {
JSDoc

2016-12-07 11:40 UTC, MadMed677 commented on server_side/route.js
> +    	return handle[pathname](response);
С индентацией проблемы

2016-12-07 11:40 UTC, MadMed677 commented on server_side/server.js
> +	const onRequest = (request, response) => {
У тебя тут индентация в табах. В Open Source проектах, принято делать на пробелах. А вот их количество уже не столь важно. Но рекомендуется 2 или 4. Тут же у тебя 8, это слишком много. Выставь в своем редакторе пожалуйста это и поправь во всех файлах.

2016-12-07 11:40 UTC, MadMed677 commented on server_side/server.js
> +    	let content = route(handle, pathname, response);
Индентация едет прям дико.

2016-12-07 11:40 UTC, MadMed677 commented on server_side/virtualWindow.js
> +let dir = __dirname.split('/');
Во-первых, операция `splice` не обладает идемпотентностью. Тут это не так страшно, но тестировать такой код будет сложнее.

Во-вторых, я не совсем понял, что ты хотел сделать, надо оставить комментарий. Но если я прав, то ты хотел просто вырезать последний элемент? Так как `dir` в итоге все равно string.
Тут есть несколько вариантов решения.

1. Превратить это в массив и работать с ним, как с массивом. Удобнее - да, быстрее - нет.
```js
const dirName = __dirname.split('/');
const dir = dirName.slice(0, dirName.length-1);
```
`slice` - идемпотентен, то есть dirName ни как не измениться. А в `dir` будет то, что ты и хотел.

2. Сделать поиск по строке, найти последний /, и вырезать все, что после него. Но я быстро не вспомню, как это сделать, мне как раз 1'ый вариант ближе. Но можешь конечно порыскать, если будет желание)

2016-12-07 11:40 UTC, MadMed677 commented on server_side/virtualWindow.js
> +let jsdom = require("jsdom").jsdom;
const

2016-12-07 11:40 UTC, MadMed677 commented on server_side/virtualWindow.js
> +const createWindow = () => {
JSDoc

2016-12-07 11:40 UTC, MadMed677 commented on src/app.js
> +let	workWithCoors = require("./helpers/index.js");
Вот тут лишняя индентация совсем не уместна.

2016-12-07 11:40 UTC, MadMed677 commented on src/app.js
> +const myBlobBuilder = new MyBlobBuilder.MyBlobBuilder();
O_O
Метод явно не должен совпадать с названием класса.

2016-12-07 11:40 UTC, MadMed677 commented on src/app.js
> +		if (err) throw err;
Неявный return. Его нужно выделить. Это конечно от code style зависит. Я потом создать .eslintrc, подведу все под стандарт, тогда таких вещей он не пропустит.

```
if (err) {
  return throw err; //  или просто `throw err;`
}
```

2016-12-07 11:40 UTC, MadMed677 commented on src/app.js
> +		lines = data.toString().split("\n");
Индентация поплыла

2016-12-07 11:40 UTC, MadMed677 commented on src/app.js
> +		workWithCoors.workWithCoors(lines, myBlobBuilder, window);
Название метода совпадает с называнием класса

2016-12-07 11:40 UTC, MadMed677 commented on src/components/myBlobBuilder.js
> +exports.MyBlobBuilder = MyBlobBuilder;
Ммм, если хочешь как в NodeJS, то лучше через `module.export = MyBlobBuilder;`

2016-12-07 11:40 UTC, MadMed677 commented on src/helpers/index.js
> +		);
Куда это она улетела?

2016-12-07 11:40 UTC, MadMed677 commented on src/helpers/index.js
> +exports.addToBlob = addToBlob;
По стандартам, в конце файла должна быть пустая строка.

2016-12-07 12:23 UTC, MadMed677 commented on public/index.html
> +           let xhr = new XMLHttpRequest();
Есть современный способ - [fetch](https://github.com/github/fetch).
Ну или хотя бы jQuery.ajax (раз ты его подключаешь)

2016-12-07 17:49 UTC, ottenokLeshi commented on server_side/virtualWindow.js
> +let dir = __dirname.split('/');
Это мой маленький велосипед))
С подключением модулей из другого каталога, в следующем коммите этого не будет))

2016-12-07 19:28 UTC, ottenokLeshi commented on package.json
> +    "webpack": "1.13.3"
А он разве не пригодится, для подключения, например, того же fetch?
Я просто исхожу из того, что в будущем может понадобиться отдавать пользователю и скрипты и что-нибудь еще.

2016-12-07 20:58 UTC, MadMed677 commented on package.json
> +    "webpack": "1.13.3"
По-хорошему все чиститься. Вообще считается, что в `dev`,а тем более в `master` не должно храниться закоменченного кода, тем более не используемого.
Но вообще, конечно, можно оставить.

2016-12-07 21:05 UTC, MadMed677 requested changes

2016-12-07 21:05 UTC, MadMed677 commented on package.json
> +    "start": "webpack | node ./server_side/index.js"
Это тоже выполнится ассинхронно? Я просто всегда писал `||` чтобы процессы друг друга не ждали, а `&&`, чтобы выполнились последовательно.

2016-12-07 21:05 UTC, MadMed677 commented on server_side/requestHandlers.js
>  let fs = require("fs");
А разве `fs` изменяется?)

2016-12-07 21:05 UTC, MadMed677 commented on server_side/index.js
>  let virtualWindow = require("./virtualWindow");
А разве `virtualWindow` меняется?)

2016-12-07 21:05 UTC, MadMed677 commented on server_side/route.js
>      	return handle[pathname](response);
Индентация

2016-12-07 21:05 UTC, MadMed677 commented on server_side/route.js
> + * @param {Array} response - ответ на запрос
Забыл добавить `@return`

2016-12-07 21:05 UTC, MadMed677 commented on server_side/server.js
>  let http = require("http");
`const'ы`

2016-12-07 21:05 UTC, MadMed677 commented on src/helpers/index.js
>  		chain = chain
А `chain` то остался на том же уровне

2016-12-07 21:05 UTC, MadMed677 commented on src/helpers/index.js
>   *Функция отвечающая за запись вычисленного значения в исходный файл
Можно считать за придирку, но пробелы должны быть после `*`. Если пользуешься WebStorm'ом, то делается шорткатом `/** + tab`. На других редакторах должно быть что-то похожее.

2016-12-11 15:23 UTC, ottenokleshi commented on server_side/route.js
>      	return handle[pathname](response);
Это странно, я у себя запустил Webstorm, Sublime и в вшитом редакторе gedit и у меня нет этого отступа, как и в index.js.
Может быть git добавляет пробелов?

2016-12-11 17:05 UTC, merged