Added Postgresql
ottenokLeshi/trafficJamsApi pull request #6
Opened 2017-02-06 15:38 UTC by ottenokLeshi

2017-02-17 08:41 UTC, MadMed677 reviewed
В целом, чуть грязновато вышло. Сейчас скажу почему.
Делать на чистом PostgreSQL, не самый лучший вариант.
Предлагаю для начала взглянуть на вот такую [ORM систему](http://docs.sequelizejs.com/en/v3/).

Это должно очень сильно вырулить код на другой уровень абстракции.

2017-02-17 13:47 UTC, MadMed677 requested changes

2017-02-17 13:47 UTC, MadMed677 commented on database_side/dataLoading.js
> +                k += 1;
Вот это такой чисто Сишный подход)
Это можно сделать не императивно, а более функционально.

Но!

Во-первых, я не могу понять, что за зверь такой, переменная `k`? Ни комментария ни нормального описания.
И чуть выше, переменная `m`. Тоже самое.

2017-02-17 13:47 UTC, MadMed677 commented on database_side/dataLoading.js
> +        lines.forEach(info => {
Бегать в цикле и пушить в базу данные выглядит не очень хорошим решением.
Думаю, это можно сделать средствами самого Postgres.
Все же взгляните на ссылку про Sequelize, через него это будет на много прозрачнее.

2017-02-17 13:47 UTC, MadMed677 commented on database_side/database.js
> +const config = {
Такие вещи нельзя хранить в репозитории, вы светите свои приватные данные.
Есть вот такой вариант. Создаете файл с конфигом `config.js`, например. Он и будет рекваириться сюда.
Но его нужно будет добавить в `.gitignore`, чтобы он лежал рядом, но в репозиторий не попадал.
Но тогда другая проблема, человек не будет знать, в каком формате ему нужен будет конфиг создавать и как он будет выглядеть. Вот для этого, надо создать файл `config.example.js` или типа того. И вот в нем уже сделать такую структуру, которая будет в основном конфиге, но уже с фейковыми данными.

Вот например так:

config.example.js
```js
module.exports = {
  database: 'my_database',
  user: 'root',
  password: null
};
```

database.js
```js
const databaseConfig = require('./config');

const config = Object.assign({}, {
  // тут можно указать дефолтный конфиг
  host: 'localhost',
  port: 5432,
  database: 'postgres'
  user: 'root',
  password: null
}, databaseConfig);
```

2017-02-17 13:47 UTC, MadMed677 commented on public/index.html
> +        let output = document.getElementById('outputRoute');
Клиентскую же логику советую вынести в отдельный файл и не встраивать его в html напрямую.

2017-02-17 13:47 UTC, MadMed677 commented on server_side/requestHandlers.js
> +            const line = [];
Писать `const line`, а потом мутировать его на 39 строке не хорошо. Это можно делать в JavaScript, потому что const проверяет лишь то, что не изменилась ссылка. Подробнее можете [тут](http://learn.javascript.ru/let-const) прочитать.
Но смысл это ломает. 

Как это можно сделать по другому? Функционально)) (я просто большой любитель функционального программирования, поэтому и советую и вам. Но обычно, это обязаловка)

Вам нужно на выходе получить массив lines, верно? А перебираете вы все через for. Можно это сделать через `.map`:

```js
// Перебираем все строки
const lines = Object.keys(data.rows).map(row => {
  const weight = parseInt(row);
  // не знаю, что такое 10000000, надо дать нормальное название переменной
  const smth = 10000000;

  if (weight === smth) {
    return `<br> id = ${data.rows[i].id} Error </br>`;
  } else {
    return `<br> id = ${data.rows[i].id} time = ${data.rows[i].weight} </br>`;
  }
});
```

Я не понял, зачем вы создаете line, и пушите в него всего 1 значение, а потом склеиваете. Может я что-то упускаю, но решил, что это лишняя операция.

Как бы то ни было, получилось читабельнее (вроде бы).

2017-02-17 13:47 UTC, MadMed677 commented on server_side/requestHandlers.js
> +            const line = [];
Но тут вы мешаете логику с view. Это плохо. Надо бы разделить, но давайте пока так.

2017-02-17 13:47 UTC, MadMed677 commented on src/app.js
> +            Object.keys(data.rows[i]).forEach(obj => {
Вот тут прям какая-то магия) Особенно ниже с кучей пушей :)

2017-03-03 08:06 UTC, MadMed677 requested changes

2017-03-03 08:06 UTC, MadMed677 commented on database_side/dataLoading.js
> +    graphArray.forEach(item => {
А зачем вы тут сделали через forEach и push? Тут ведь тоже явно можно сделать через `map`

2017-03-03 08:06 UTC, MadMed677 commented on database_side/dataLoading.js
> +    const linesPromise = new Promise(resolve => createTable(lines).then(() => {
Надо также рассмотреть вариант, если что-то не удалось и promise creators возвращает вам не resolve, а `reject`

2017-03-03 08:06 UTC, MadMed677 commented on database_side/dataLoading.js
> +    const pointsPromise = new Promise(resolve => createTable(points).then(() => {
Вы оборачиваете промис, в промис :)
То есть createTable возвращает вам промис. А вы его потом еще раз в него оборачиваете.

Можете опустить конструкцию `new Promise`. Сделать прямой вызов createTable, описать логику того, что должно вызываться. А в конце вызвать не `resolve()`, а просто return данных.

2017-03-03 08:06 UTC, MadMed677 commented on database_side/databaseMethods.js
> +const readDb = (table, parametrs) => table.findAll(parametrs)
Тут все же надо подумать, как лучше оформить. Так выглядит слишком длинно.
Можно сделать вот так:

```js
const readDb = (table, parameters) => {
  return table
    .findAll(parameters)
    .catch(err => console.log(`Database errors: ${err}`));
};
```

На самом деле я тоже пытался всегда опустить слово `return`, если это возможно. Но меня всегда на ревью били за это) Нужно чтобы код был удобочитаемым. Если код короче, это не означает, что он удобочитаемый.

2017-03-03 08:06 UTC, MadMed677 commented on database_side/databaseMethods.js
> +const readDb = (table, parametrs) => table.findAll(parametrs)
И еще, у типа `Object` нет ни метода `.find`, ни `.findAll`. Вот у массива есть метод `.find`, но `.findAll` нету. Вы не ошиблись?

2017-03-03 08:06 UTC, MadMed677 commented on database_side/databaseMethods.js
> +const updateDb = (table, element, parametrs) => table.update(element, parametrs)
Тут по аналогии с комментарием выше

2017-03-03 08:06 UTC, MadMed677 commented on database_side/databaseMethods.js
> +const deleteDb = (table, parametrs) => table.destroy(parametrs)
То же самое

2017-03-03 08:06 UTC, MadMed677 commented on database_side/databaseMethods.js
> +const readDb = (table, parametrs) => table.findAll(parametrs)
А стоп, я понял. Это не инстанс `Object`, это инстанс таблицы от Sequelize?
Если так, то это надо и написать в типах. Так как `Object` такими методами не обладает.

2017-03-03 08:06 UTC, MadMed677 commented on database_side/models/points.js
> +const points = sequelize.define('points', {
Создание моделей ([Model definition](http://docs.sequelizejs.com/en/v3/docs/models-definition/)) это как создание классов по сути. Некая абстрактная модель. И в доке ее называют с заглавной буквы, чтобы это подчеркнуть.

```js
const Points = requilize.define('points', {
  ...
});
```

2017-03-03 08:06 UTC, MadMed677 commented on server_side/requestHandlers.js
> +            lines.push(line);
Тот вариант, что я описал не сработал? Почему оставили так?

2017-03-03 08:06 UTC, MadMed677 commented on src/app.js
> +                return [
Ай ай. Выглядит достаточно плохой практикой.
Вы тут заполняете массив данными. Что это за данные, вы не описали. В итоге, на выход получаете массив с 7 элементами и что в какой последовательности идет, совершенно не понятно.

Тут 2 варианта. Или сделать это не массив, а объект. Где ключ может быть название поля, а значение - значением :)
```js
{
  id: line.id,
  begin_p: line.begin_p,
  ...
}
```

Такой формат поможет вам в будущем, при использовании этого ~~массива~~ объекта, вычленять данные не по индексам `array[0]`, `array[1]`. А по нормальным названиям `object['id']`, `object['begin_p']`. Но и тут надо описать, что означает каждое из полей.

Второй вариант, подробно описать, но оставить как массив.

2017-03-03 08:06 UTC, MadMed677 commented on src/app.js
> +                    line.begin_point.point.coordinates[1],
Если у begin_point не будет объекта `point`, ваш код упадет. Можете взглянуть на функцию lodash'а - [_.get](https://lodash.com/docs#get)

2017-03-03 08:06 UTC, MadMed677 commented on src/helpers/index.js
>      if (coors[1] === 43 || coors[2] === 43 || coors[1] === 201 || coors[2] === 201 || coors[1] === 251 ||
Повторюсь, такой if с проверками, это порнография. С этом явно надо что-то сделать. Например, вынести проверку в функцию и описать, что же это за злобные проверки. А тут лишь ее вызвать.

```js
if (validateCoors(coors)) {
  ...
}
```

Тут название функции не самое удачное, надо над ним еще подумать.

2017-03-03 08:06 UTC, MadMed677 commented on database_side/dataLoading.js
> +            id: item[0],
Про это оставил комментарий ниже.

2017-03-03 08:06 UTC, MadMed677 commented on database_side/dataLoading.js
> +        const edge = item;
Вот это на самом деле странная операция, так как копирования, как предполагается, не произойдет, item это объект, так что вы просто скопируете ссылку и назовете ее по другому. Смысла в этом нет.
Думаю, вам пригодится что-то вроде [_.omit](https://lodash.com/docs#omit)

2017-03-03 14:00 UTC, ottenokLeshi commented on database_side/dataLoading.js
> +    graphArray.forEach(item => {
Для меня не совсем очевидны преимущества варианта с map в данном случае. Получается, что мы сначала сделаем большущий массив из объектов, а затем нам придется убрать повторяющиеся.

В моем же случае я создаю 255 объектов, вместо 1066, и сразу могу их использовать.

2017-03-03 14:13 UTC, ottenokLeshi commented on database_side/dataLoading.js
> +        const edge = item;
Аналогично ли это будет созданию объекта через `new Object(...)`?

2017-03-03 14:16 UTC, ottenokLeshi commented on src/app.js
> +                    line.begin_point.point.coordinates[1],
Есть какие-то правила задания значений по-умолчанию?
(Ноль, который первым приходит в голову, тут не годится, потому что в Postgres стоит NOT NULL везде)

2017-03-05 07:43 UTC, MadMed677 commented on database_side/dataLoading.js
> +        const edge = item;
Честно говоря, не использовал конструктор `new Object` уже года 2-3 уже.
Если хотите склонировать объект, вот прям 1 в 1, то лучше делать через `const edge = Object.assign({}, item);`. Вот `Object.assign` это точно копирующий статичный метод. Можете посмотреть как он работает.

2017-03-06 07:40 UTC, MadMed677 requested changes
Небольшие правки. В остальном все ок.

2017-03-06 07:40 UTC, MadMed677 commented on database_side/dataLoading.js
> +    graphArray.forEach(item => {
Да, `map` должен вернуть именно столько же элементов, сколько было в изначальном массиве. Но это все равно можно сделать функционально. Как вариант, вы делаете все то же самое, только в условии `if`, делаете не `push` данных, а `return`. А иначе ничего не возвращаете.
В итоге у вас получится массив, состоящий из нужных вам элементов + `undefined`.
После этого, вы просто делаете `.filter(e => !_.isUndefined(e));`. После этой операции, у вас на выходе будет чистый массив, который вам и нужен.

2017-03-06 07:40 UTC, MadMed677 commented on src/app.js
> +                    line.begin_point.point.coordinates[1],
Все точно так же как и обычным присваиванием, только передаете 3'им аргументом. А `Not Null` !== 0? Не совсем понял вопроса на самом деле)

2017-03-06 07:40 UTC, MadMed677 commented on database_side/databaseMethods.js
> + * @param {Object} table - Sequelize-объект, таблица из /models/
Не, немного не то) Я про
`@param {Object}` должен быть чем-то вроде `@param {Models}`

2017-03-06 07:40 UTC, MadMed677 commented on database_side/databaseMethods.js
>           .catch(err => console.log(`Database error: ${err}`));
Лишний `space`

2017-03-06 07:40 UTC, MadMed677 commented on server_side/requestHandlers.js
> +    /*
Комментарии кода в .git обычно не хранят

2017-03-06 07:40 UTC, MadMed677 commented on src/app.js
> +                    id: _.get(line, 'id', 1),
_.get, это безопасный способ получения данных. Его используют, если структура достаточно вложенная.
Если заглянуть в исходники, то можно увидеть, что он делает рекурсивный вызов данных. Поэтому, если можно сделать получение данных не через _.get, то лучше делать без него.

`line.id || 1` тоже самое, что `_.get(line, 'id', 1)`. Только второе антипаттерн.

2017-03-09 15:27 UTC, MadMed677 approved these changes

2017-03-09 15:27 UTC, MadMed677 commented on database_side/dataLoading.js
> +    let pointsArray = [];
Не нужно ведь его декларировать заранее. Сделай сразу 

```js
const pointsArray = graphArray.map(...)
```

2017-03-09 15:27 UTC, MadMed677 commented on database_side/dataLoading.js
> +            counter += 1;
Зачем `counter`? Он ведь больше не используется

Upd. console.log ведь не считается. Если нужен индекс, то map принимает его 2'ым параметром

2017-03-09 15:38 UTC, ottenokLeshi commented on database_side/dataLoading.js
> +            counter += 1;
Если посмотреть файл input.txt, там второе число в строке - id вершины, пользуясь тем, что они идут по порядку, я прохожу map-ом.
В данном случае `counter` нужен чтобы проверить: занесли ли мы уже в `pointsArray` точку или нет:)

2017-03-09 15:41 UTC, merged