Added ExpressJS and functions for returning file and json
ottenokLeshi/trafficJamsApi pull request #8
Opened 2017-03-21 11:46 UTC by ottenokLeshi

2017-03-30 17:54 UTC, MadMed677 requested changes

2017-03-30 17:54 UTC, MadMed677 commented on package.json
>      "babel-preset-stage-0": "6.16.0",
Stage 0 лучше убрать

2017-03-30 17:54 UTC, MadMed677 commented on public/script.js
>  const getData = () => {
Если функция больше не нужна, надо удалять

2017-03-30 17:54 UTC, MadMed677 commented on server_side/requestHandlers.js
> +const getRoutesInTXT = response => {
Функция асинхронная, надо вернуть значение, иначе это как сайд эффект

2017-03-30 17:54 UTC, MadMed677 commented on server_side/requestHandlers.js
> +const getRoutesInJSON = response => {
Асинхронная функция, нужен промис

2017-03-30 17:54 UTC, MadMed677 commented on server_side/server.js
> +exports.app = app;
Зачем экспортируете? Все что связано напрямую с роутингом, не нужно экпортировать. Вынесите тогда отдельно в роут.

2017-03-30 17:54 UTC, MadMed677 commented on src/helpers/index.js
> +    return methodsDb.updateDb(lines,
Во,  тут верно вернули

2017-04-03 08:40 UTC, ottenokLeshi commented on server_side/server.js
> +exports.app = app;
Думал, что пригодится где-нибудь, да потом забыл стереть.

2017-04-10 08:05 UTC, MadMed677 approved these changes

2017-04-10 08:49 UTC, merged